propose-time-window = 240
challenge-time-window = 3
l2-starting-number = $OPBNB_BRIDGE_BOT_L2_STARTING_NUMBER

[rpcs]
l1-rpc = "$OPBNB_BRIDGE_BOT_L1_RPC"
l2-rpc = "$OPBNB_BRIDGE_BOT_L2_RPC"

[tx-signer]
privkey = "$OPBNB_BRIDGE_BOT_PRIVKEY"
gas-price = 5000000000 # 5 gwei

[db]
host = "$OPBNB_BRIDGE_BOT_DB_HOST"
port = $OPBNB_BRIDGE_BOT_DB_PORT
user = "$OPBNB_BRIDGE_BOT_DB_USER"
password = "$OPBNB_BRIDGE_BOT_DB_PASSWORD"
name = "$OPBNB_BRIDGE_BOT_DB_NAME"

[l1-contracts]
optimism-portal                 = "0x4386c8abf2009ac0c263462da568dd9d46e52a31"
l2-output-oracle                = "0xff2394bb843012562f4349c6632a0ecb92fc8810"
l1-cross-domain-messenger       = "0xd506952e78eecd5d4424b1990a0c99b1568e7c2c"

[l2-standard-bridge-bot]
contract-address                = "0x62fa6549e240076D466E1150ce587905c55f12F1"
log-filter-block-range = 1000

# See https://github.com/bnb-chain/opbnb-bridge-tokens#opbnb-testnet-token-list
whitelist-l2-token-list = [
    "0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000", # Native token
    "0xa9aD1484D9Bfb27adbc2bf50A6E495777CC8cFf2", # BUSD
    "0x3AB4E696E31173409dbfBb1FEB5b9A7cC55A212c", # BTCB
    "0x584f7b986d9942B0859a1E6921efA5342A673d04", # ETH
    "0xCF712f20c85421d00EAa1B6F6545AaEEb4492B75", # USDT
    "0x845E27B8A4ad1Fe3dc0b41b900dC8C1Bb45141C3", # USDC
    "0xf46896fbEf6478eaCcFB1C815915daa7e6f87b22", # DAI
    "0x2C58b64b4BA448A9b60e9398E58d17F1824da962"  # tBEP20
]
